### ISSUE TITLE
Add Swift Package Manager support ? 

### ISSUE THREAD

**Issue by kohlivarun5** [near/near-api-swift#2]
Would be great if we could import this using Swift Package Manager. If it helps, I tried adding some support [here](https://github.com/kohlivarun5/near-api-swift), but the code fails to compile. Help getting this working on latest iOS would be greatly appreciated

**Comment by samingle** [comment]
Hey, we were recently granted maintainer access to this repository. While it'll be a while before we'll be able to get to Swift Package Manager support ourselves, we'd welcome a PR.

**Comment by frol** [comment]
@samingle Should this issue be closed given #12 was merged?

**Comment by samingle** [comment]
it should, we've moved on to other projects, looks like we no longer have the perms to close issues.
